networks:
  xpaywall-net:
    driver: bridge

services:
  adminpanel:
    build:
      context: ./frontend/adminpanel
      dockerfile: Dockerfile
      args:
        VITE_APP_BASE_NAME: /
    image: philpher/xpaywall-adminpanel:latest
    container_name: xpaywall-adminpanel
    restart: unless-stopped
    networks:
      - xpaywall-net
    depends_on:
      - control-api
    environment:
      API_URL: http://127.0.0.1:3101/
      PROXY_URL: http://127.0.0.1:3102/
    ports:
      - "3100:80"

  control-api:
    build:
      context: ./control-api
      dockerfile: Dockerfile
    image: philpher/xpaywall-control-api:latest
    container_name: xpaywall-control-api
    restart: unless-stopped
    networks:
      - xpaywall-net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONTROL_DB_DSN: postgres://user:password@xpaywall-postgres:5432/xpaywalldb?sslmode=disable
      PORT: 9091
      MODE: release
      INTERNAL_API_KEY: change-me-internal-secret-key
      JWT_SECRET: change-me-jwt-secret-key
      PROXY_URL: http://localhost:8081
      SUPERADMIN_USERNAME: superadmin
      SUPERADMIN_PASSWORD: superadmin
    ports:
      - "3101:9091"

  xgateway:
    build:
      context: ./xgateway
      dockerfile: Dockerfile
    image: philpher/xpaywall-xgateway:0.1.1
    container_name: xpaywall-xgateway
    restart: unless-stopped
    networks:
      - xpaywall-net
    depends_on:
      - control-api
    environment:
      PORT: 8081
      LOG_LEVEL: INFO
      CONFIG_PROVIDER: http
      CONTROL_API_URL: http://xpaywall-control-api:9091
      INTERNAL_API_KEY: change-me-internal-secret-key
      GIN_MODE: release
    ports:
      - "3102:8081"

  example-server:
    build:
      context: ./examples/server
      dockerfile: Dockerfile
    image: philpher/xpaywall-example-server:latest
    container_name: xpaywall-example-server
    restart: unless-stopped
    networks:
      - xpaywall-net
    ports:
      - "3103:4021"

  postgres:
    image: postgres:16
    container_name: xpaywall-postgres
    restart: unless-stopped
    networks:
      - xpaywall-net
    environment:
      POSTGRES_DB: xpaywalldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5482:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d xpaywalldb" ]
      interval: 5s
      timeout: 5s
      retries: 10
